In [281]:
import numpy as np
import torch

# data

In [282]:
X = [[1,1],[1,0],[1,2],[1.5,1.2],[1.2,1.3],[1,2],
           [3,4],[3,4.2],[3,5],[4,4],[3.4,4]]
y = [0,0,0,0,0,0,1,1,1,1,1]
X = np.array(X)
y = np.array(y).reshape(-1,1)

In [283]:
X.shape,y.shape

((11, 2), (11, 1))

In [284]:
def sigmoid(z):
    return 1 / (1 + torch.exp(-z))

m,n = X.shape
num_layer1 = 3
W_1 = np.random.rand(num_layer1,n)
b_1 = np.random.rand(1,num_layer1)
W_1_tensor = torch.tensor(W_1, requires_grad=True)
b_1_tensor = torch.tensor(b_1, requires_grad=True)
def forward(X,W,b):
    """
    W is ndarray with shape of number of neurons * number of input features(last layer neurons)
    X is ndarray with shape of number of dataset * number of features
    b is vector of number of neurons * 1"""
    Z = torch.matmul(X,W.T) + b
    return sigmoid(Z)
X_tensor = torch.tensor(X,dtype=float)
A_1 = forward(X_tensor,W_1_tensor,b_1_tensor)
X.shape,W_1_tensor.shape,b_1_tensor.shape

((11, 2), torch.Size([3, 2]), torch.Size([1, 3]))

In [286]:
num_layer2 = 1
W_2 = np.random.rand(num_layer2,len(A_1[0]))
b_2 = np.random.rand(1,num_layer2)
W_2_tensor = torch.tensor(W_2, requires_grad=True)
b_2_tensor = torch.tensor(b_2, requires_grad=True)
A_2 = forward(A_1,W_2_tensor,b_2_tensor)
A_2.shape,A_1.shape,W_2_tensor.shape,b_2_tensor.shape

(torch.Size([11, 1]),
 torch.Size([11, 3]),
 torch.Size([1, 3]),
 torch.Size([1, 1]))

In [288]:
y = torch.tensor(y)
loss =(1/m) * sum(-y*torch.log(A_2)-(1-y)* torch.log(1-A_2))

In [289]:
loss

tensor([1.2717], dtype=torch.float64, grad_fn=<MulBackward0>)

In [290]:
loss.backward()

In [291]:
lr = 0.0001
for i in range(1000):
    A_1 = forward(X_tensor,W_1_tensor,b_1_tensor)
    A_2 = forward(A_1,W_2_tensor,b_2_tensor)
    loss =(1/m) * sum(-y*torch.log(A_2)-(1-y)* torch.log(1-A_2))
    loss.backward()
    W_1_tensor.data = W_1_tensor.data - lr* W_1_tensor.grad.data
    b_1_tensor.data = b_1_tensor.data - lr* b_1_tensor.grad.data
    W_2_tensor.data = W_2_tensor.data - lr* W_2_tensor.grad.data
    b_2_tensor.data = b_2_tensor.data - lr* b_2_tensor.grad.data
    print(loss)

tensor([1.2717], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2715], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2713], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2711], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2707], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2703], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2698], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2693], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2687], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2680], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2672], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2664], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2655], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2645], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2635], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.2624], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([

tensor([0.8001], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7957], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7913], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7870], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7827], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7785], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7744], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7703], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7663], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7624], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7585], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7546], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7509], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7472], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7436], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.7401], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([

tensor([1.0292], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0336], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0380], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0424], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0467], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0510], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0553], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0596], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0638], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0680], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0721], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0762], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0803], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0844], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0884], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0924], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([

tensor([1.1859], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1832], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1804], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1776], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1747], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1717], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1687], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1657], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1626], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1595], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1563], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1531], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1499], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1465], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1432], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.1398], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([

tensor([0.6559], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6572], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6585], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6599], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6614], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6630], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6647], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6664], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6682], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6701], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6721], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6742], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6763], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6785], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6808], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([0.6831], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([

tensor([1.0928], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0930], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0932], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0932], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0932], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0932], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0931], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0929], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0927], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0925], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0921], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0917], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0913], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0908], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0902], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([1.0896], dtype=torch.float64, grad_fn=<MulBackward0>)
tensor([

In [304]:
inp = torch.tensor([[-5120,-50000]],dtype=float)
A = forward(inp,W_1_tensor,b_1_tensor)
A_22 = forward(A,W_2_tensor,b_2_tensor)
A_22

tensor([[0.5707]], dtype=torch.float64, grad_fn=<MulBackward0>)